/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "glbdputmlsrsaeclujbo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsYmRwdXRtbHNyc2FlY2x1amJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzU2ODMsImV4cCI6MjA3Nzk1MTY4M30.3fOoFm0P1sglEBEeQjrk-YXFcjArY27xcYjtPTafI-E"